### ISSUE TITLE
Send client remaining funds when a contract fails

### ISSUE THREAD

**Issue by emizzle** [codex-storage/codex-contracts-eth#98] opened 2024-04-15 12:54 UTC
When a contract completes (succeeds or fails), send client remaining funds.

**Comment by emizzle** [comment] 2024-04-22 08:02
In the case of failure, do we refund the entire amount to the client? Or is this incentive for the client to attack the storage providers that have filled the slots towards the end of the contract?

**Comment by AuHau** [comment] 2024-07-11 12:26
Just a note. I was wondering if there are any client's funds remaining in case of successfully finishing the storage request, because I thought it will be paid out to the SPs. But with this https://github.com/codex-storage/codex-contracts-eth/issues/102 in, there could be some amount of funds left. Btw. it might be a bit of nightmare to track it correctly 😅 Lets see.

**Comment by AuHau** [comment] 2024-09-02 08:28
Duplicate of https://github.com/codex-storage/codex-contracts-eth/issues/98

**Closed by AuHau** 2024-09-02 08:28 UTC
Labels: Marketplace
